# docker-compose.yml

services:

  apachehttp:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:80" # Map container's port 80 to port 1234 on the host machine
    restart: always

  # The below is taken from https://github.com/leosmitt/container-cloudflare-tunnel/
  # This segment is released under the GNU Lesser General Public License v3
  # See https://github.com/leosmitt/container-cloudflare-tunnel/main/LICENSE for more details
  cloudflare-tunnel:
    image: cloudflare/cloudflared
    container_name: cloudflare-tunnel
    hostname: cloudflare-tunnel
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    network_mode: "host"
    command: tunnel run
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "TUNNEL_TOKEN=eyJhIjoiNWIyOWJjZTNiMjA2MWY4MjEwYzAxM2YyYmM2NzQ3MGEiLCJ0IjoiZGIxODIyZWYtMWI4Zi00MmE0LWJlNjgtMTgzNjk2NDMxMDkwIiwicyI6Ik1HSTFZekF5Tm1NdE1HTTJaQzAwWVdWa0xXRTNaVGN0TldGaFptSXdPV0V4TjJVNSJ9"
    healthcheck:
      test: ["CMD", "cloudflared", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      # enbale watchtower updates
      - "com.centurylinklabs.watchtower.enable=true"
